# SITE CONFIGURATION
baseurl: ""
url: "https://blog.night-shade.org.uk/"
title: A travelling tinker
description: 'Things I&#039;ve fixed, places I&#039;ve been'


# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: A travelling tinker
  avatar: assets/img/TinkerTool-icon.png
  favicon: assets/favicon.ico
  gravatar: 96688e2b870da5be9d2f5d33612764ad

  # Header and footer text
  header_text: > #two or three lines to describe your site
    Things I&#039;ve fixed, places I&#039;ve been
  header_text_feature_image: wp-content//uploads/2011/12/cropped-IMG_4148-Blog-Header.jpg
  footer_text: >
    Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a>

  # Icons
  rss: true  # Make sure you created a feed.xml with feed.xml layout
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: timjdfletcher
  google_plus:
  instagram: timjdfletcher
  keybase: timjdfletcher
  linkedin: https://www.linkedin.com/in/timjdfletcher
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: timjdfletcher
  vimeo:
  wordpress:
  youtube:
# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
katex: true                                             # Enable if using math markup
google_analytics:                                       # Tracking ID, e.g. "UA-000000-01"
disqus_shortname:                                       # Your discus shortname for comments
layout_variables:                                       # Open the "_sass > base" folder, and open "_variables.scss"
footer_icons:                                           # In _data/social.yml
share_buttons:                                          # In _data/social.yml
authors:                                                # In _data/authors.yml
language:                                               # In _data/language.yml

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", "Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", ".idea", "vendor/*",
          "LICENSE", "README.md", "screenshot.png", "assets/package.json", "assets/node_modules", "assets/gulpfile.js"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
