# SITE CONFIGURATION
baseurl: ""
url: "https://blog.night-shade.org.uk"
title: A travelling tinker
description: 'Things I&#039;ve fixed, places I&#039;ve been'


# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: A travelling tinker
  avatar: assets/img/triangle.svg
  favicon: assets/favicon.ico
  gravatar: 96688e2b870da5be9d2f5d33612764ad

  # Header and footer text
  header_text: > #two or three lines to describe your site
    Things I&#039;ve fixed, places I&#039;ve been
  header_text_feature_image: wp-content//uploads/2011/12/cropped-IMG_4148-Blog-Header.jpg
  footer_text: >
    Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a>

  # Icons
  rss: true  # Make sure you created a feed.xml with feed.xml layout
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: timjdfletcher
  google_plus:
  instagram: timjdfletcher
  keybase:
  linkedin: https://www.linkedin.com/in/timjdfletcher
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: timjdfletcher
  vimeo:
  wordpress:
  youtube:

  # Scripts / Features 
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup
  
  special_page:
    search: 
      icon: "search" # Assuming page link and icon are the same
      enabled: true
    tags:
      icon: "tags"
      enabled: true
  
  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true
  
  
# PAGINATION
paginate: 5
paginate_path: "blog/page:num"


# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name


# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag]
#theme: type-on-strap # Uncomment if using the theme as a jekyll theme gem
exclude: ["Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", ".gemcache", "LICENSE", "README.md", "screenshot.png"]
